version: "3"
services:
    myapp:
        image: "myapp:dev"
        build:
            context: .
            dockerfile: Dockerfile
        hostname: myapp
        stdin_open: true
        tty: true
        working_dir: '/myapp-dev'
        volumes:
            - ".:/myapp-dev"
